[package]
name = "sample"
version = "0.0.0"
edition = "2021"

[dependencies]
log = "0.4"
pretty_env_logger = "0.2"
serde_derive = "1"
url = "2"

[dependencies.clap]
version = "3"
features = ["derive"]
