name: CI
on:
  - push
  - pull_request
jobs:
  build:
    name: ${{ matrix.os }} (${{ matrix.rust }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust:
          - 1.58.0
          - stable
          - beta
          - nightly
        # https://github.com/actions/virtual-environments#available-environments
        os:
          - macOS-10.15
          - macOS-11
          - macOS-12
          - ubuntu-18.04
          - ubuntu-20.04
          - ubuntu-22.04
          - windows-2019
          - windows-2022
    steps:

    - uses: actions/checkout@v3

    - name: Install ${{ matrix.rust }} toolchain
      uses: dtolnay/rust-toolchain@master
      with:
          toolchain: ${{ matrix.rust }}

    - name: Build
      run: cargo build

    - name: Generate files
      run: cargo run resources/spec.yml resources/sample/src --override-impl

    - name: Test that generated files compile
      run: cargo build --manifest-path resources/sample/Cargo.toml

  security-audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/audit-check@v1.2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
